### PR TITLE
fix #1 add and fix a bunch of travis checks

### LINKED ISSUE #1: Travis Cleanup
Seems like Travis was failing we need to clean it up and verify things are working again.

### PR DESCRIPTION
**Pull request by dmlb2000**
This adds more pylint and more unit tests to the travis-ci engine.

### CODE REVIEW

**Comment by dmlb2000** [comment]
Coverage report from travis...

```
+coverage report -m
Name                         Stmts   Miss  Cover   Missing
----------------------------------------------------------
index_server_orm.py             21      0   100%
index_server_unit_tests.py      72      1    99%   116
index_server_utils.py           26      1    96%   21
----------------------------------------------------------
TOTAL                          119      2    98%
```

**Comment by dmlb2000** [comment]
@derekhop I think the big issue for why unit test were failing was that the connect and close was in the update_index method... I moved that to the calling method in FileIndexServer.py and the unit tests started passing... 

Seems like the docker containers work as well...

**Comment by derekhop** [comment]
Thanks will check it out.

dfh

On Sep 9, 2016, at 11:32 PM, David Brown <notifications@github.com<mailto:notifications@github.com>> wrote:


@derekhop<https://github.com/derekhop> I think the big issue for why unit test were failing was that the connect and close was in the update_index method... I moved that to the calling method in FileIndexServer.py and the unit tests started passing...

Seems like the docker containers work as well...

**Comment by dmlb2000** [comment]
Yeah, I think a db close when using a sqlite in-memory database kinda blows the database away...

**Comment by derekhop** [comment]
I see and believe I understand what you did and how that fixed things with the unit tests.

**Pull request merged**
